//
//  main.swift
//  CSCI495-FA2022
//
//  Created by Joon Suk Lee on 10/6/22.
//
//  DO NOT EDIT THIS FILE

import Foundation

// main.swift is the entry point of any swift program.
// Read "Files and Initialization" (https://developer.apple.com/swift/blog/?id=7)

func runP001() {
    let obj = P001()
    let result = obj.findSumOfMultiplesOf3n5(until: 1000)
    print ("The result is \(result)")
}

func runP002() {
    let obj = P002()
    let result = obj.sumOfEvenValuedFibonacciTerms(maxFibonacciNumber: 4_000_000)
    print ("The result is \(result)")
}

func runP003() {
    let obj = P003()
    let result = obj.largestPrimeFactor(600_851_475_143)
    print ("The result is \(result)")
}

func runP004() {
    let obj = P004()
    let result = obj.findLargestPalindrome()
    print ("The largest is \(result)")
}

func runP005() {
    let obj = P005()
    let result = obj.findSmallestPositiveNumber(divisibleByOneToN: 20)
    print ("The smallest number dividable with all number 1-20 is \(result)")
}

func runP006() {
    let obj = P006()
    let result = obj.findSolution(100)
    print ("The difference between the square of sum and sum of squares for 1-100 is \(result)")
}

func runP007() {
    let obj = P007()
    let result = obj.findSolution(10001)
    print ("The result is \(result)")
}


runP001()
