//
//  P002.swift
//  CSCI495-FA2022
//
//  Created by Joon Suk Lee on 10/6/22.
//

import Foundation

/********************** Problem 02 *********************************
 * Each new term in the Fibonacci sequence is generated by adding
 * the previous two terms. By starting with 1 and 2, the first 10
 * terms will be:
 *
 *   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values
 * do not exceed four million, find the sum of the even-valued terms.
 *******************************************************************/

struct P002 {
    
    func sumOfEvenValuedFibonacciTerms(maxFibonacciNumber max : Int) -> Int {
      
        return 0
    }
}
